models/User.php
<?php

class User extends CActiveRecord
{
	/**
	 * The followings are the available columns in table 'tbl_user':
	 * @var integer $id
	 * @var string $username
	 * @var string $password
	 * @var string $email
	 * @var string $profile
	 */

    public $acess_level;

	/**
	 * Returns the static model of the specified AR class.
	 * @return CActiveRecord the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{user}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('username, password, email', 'required'),
			array('username, password, email', 'length', 'max'=>128),
			array('access_level, session, social', 'safe'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'posts' => array(self::HAS_MANY, 'Post', 'author_id'),
            'profile'=>array(self::HAS_ONE, 'Profile', 'user_id'),
            'comments' => array(self::HAS_MANY, 'Gcomments', 'user_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'Id',
			'username' => 'Username',
			'password' => 'Password',
			'email' => 'Email',
            'access_level' => 'Access level',
            'social' => 'OpenID Md5'
		);
	}

    public function getName() {
        return (isset($this->profile->nick) && $this->profile->nick != "") ? $this->profile->nick : $this->username;
    }

	/**
	 * Checks if the given password is correct.
	 * @param string the password to be validated
	 * @return boolean whether the password is valid
	 */
	public function validatePassword($password)
	{
		return crypt($password,$this->password)===$this->password;
	}

	/**
	 * Generates the password hash.
	 * @param string password
	 * @return string hash
	 */
	public function hashPassword($password)
	{
		return crypt($password, $this->generateSalt());
	}

	/**
	 * Generates a salt that can be used to generate a password hash.
	 *
	 * The {@link http://php.net/manual/en/function.crypt.php PHP `crypt()` built-in function}
	 * requires, for the Blowfish hash algorithm, a salt string in a specific format:
	 *  - "$2a$"
	 *  - a two digit cost parameter
	 *  - "$"
	 *  - 22 characters from the alphabet "./0-9A-Za-z".
	 *
	 * @param int cost parameter for Blowfish hash algorithm
	 * @return string the salt
	 */
	protected function generateSalt($cost=10)
	{
		if(!is_numeric($cost)||$cost<4||$cost>31){
			throw new CException(Yii::t('Cost parameter must be between 4 and 31.'));
		}
		// Get some pseudo-random data from mt_rand().
		$rand='';
		for($i=0;$i<8;++$i)
			$rand.=pack('S',mt_rand(0,0xffff));
		// Add the microtime for a little more entropy.
		$rand.=microtime();
		// Mix the bits cryptographically.
		$rand=sha1($rand,true);
		// Form the prefix that specifies hash algorithm type and cost parameter.
		$salt='$2a$'.str_pad((int)$cost,2,'0',STR_PAD_RIGHT).'$';
		// Append the random salt string in the required base64 format.
		$salt.=strtr(substr(base64_encode($rand),0,22),array('+'=>'.'));
		return $salt;
	}

}

controllers/UserController.php
<?php

class UserController extends Controller
{
	public $layout='column2';
    public $user_id = false;

    private $_model = null;

	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to access 'index' and 'view' actions.
                'actions'=>array('index', 'view', 'send', 'getMessages', 'points', 'setUserLang', 'setIosFind'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated users to access all actions
                'actions' => array('edit', 'uploadAvatar', 'addComment', 'deleteComment', 'createChanel', 'changeChanel', 'updateActiveUser', 'setUserLang'),
                'users'=>array('@'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function getUserId() {
        $user_id = Yii::app()->user->getState('profile_id');
        if(!$user_id)
            $user_id = Yii::app()->user->id;
        return $user_id;
    }

    public function actionIndex() {

        $model = User::model()->findAll();
        $this->render('index', array('model' => $model));
    }

	public function actionView() {

        $model = $this->loadModel();
        $this->render('view',array('data'=>$model));
    }

    public function actionSetUserLang() {
        Yii::app()->user->setState('lang_redirect', 1);
        echo json_encode(array("lang_redirect" => "true"));
        Yii::app()->end();
    }

    public function actionSetIosFind() {
        Yii::app()->user->setState('ios_redirect', true);
        echo json_encode(array("ios_redirect" => "true"));
        Yii::app()->end();
    }

    public function actionAddComment() {
        $errors = null;

        if(isset($_REQUEST['gameid']) && $_POST['text']) {

            $comment_model = new Gcomments();
            $comment_model->gameid = $_REQUEST['gameid'];
            $comment_model->user_id = $this->getUserId();
            $comment_model->text = strip_tags($_POST['text']);
            $comment_model->date = time();
            $comment_model->save();
            $errors = $comment_model->getErrors();

        }

        $model = Game::model()->findByAttributes(array(
            "gameid" => $_REQUEST['gameid'],
        ));

        $this->renderPartial('_game_comment_list', array(
            'data' => $model,
            'errors' => $errors,
        ));
    }


    public function actionDeleteComment() {

        if(isset($_REQUEST['gameid']) && isset($_REQUEST['id'])) {

            Gcomments::model()->deleteAllByAttributes(array(
                "gameid" => $_REQUEST['gameid'],
                "id" => $_REQUEST['id'],
                "user_id" => $this->getUserId(),
            ));
        }

        $model = Game::model()->findByAttributes(array(
            "gameid" => $_REQUEST['gameid'],
        ));

        $this->renderPartial('_game_comment_list', array(
            'data' => $model,
        ));

    }

    public function actionEdit() {

        $model = $this->loadModel();
        if($model->id != $this->getUserId())
            throw new CHttpException(404, Controller::trans('The requested page does not exist.'));

        if($_POST) {
            if($_POST['avatar'] != "false") {
                $serverUserDir = Controller::rootDir() . Yii::app()->params['images_user'] . '/' . $this->getUserId();
                if(copy($serverUserDir . '/temp_avatar.jpg', $serverUserDir . '/avatar.jpg')) {
                    $model->profile->avatar = Yii::app()->params['images_user'] . '/' . $this->getUserId() . '/' . 'avatar.jpg';
                }
            }
            $model->profile->attributes = $_POST['Profile'];
            $model->profile->save();
        }
        $this->render('edit',array('data'=>$model));
    }

    public function actionGetMessages() {
        $dbfile = dirname(__FILE__) . "/../data/chat.db";
        $chat_array = unserialize(file_get_contents($dbfile));
        $this->widget('bootstrap.widgets.TbMenu', array(
            'type' => 'list',
            'items' => $chat_array,
        ));
    }

    public function actionSend() {

        $user_id = $this->getUserId();
        if(!$user_id) {
            echo json_encode(array(
                'result' => true,
                'message' => CHtml::tag("a", array(
                    'href' => Yii::app()->createUrl('site/login'),
                ), "Please login..."),
            ));
            die();
        }


        $msg = (isset($_POST['msg'])) ? $_POST['msg'] : false;
        if($msg) {
            $chat_array = array();
            $chanel = (isset($_GET['chanel'])) ? $_GET['chanel'] : false;
            $dbfile = dirname(__FILE__) . "/../../chat_data/" . $chanel . ".txt";
            if(!is_file($dbfile)) {

                $chat_array[] = array(
                    'username' => Yii::app()->user->name,
                    'userid' => Yii::app()->user->id,
                    'text' => CHtml::encode($msg),
                    'id' => $id = 0,
                );

            } else {

                $chat_array = json_decode(file_get_contents($dbfile));
                if(is_array($chat_array) && count($chat_array) > 19) {
                    array_shift($chat_array);
                }
                $chat_array[] = array(
                    'username' => Yii::app()->user->name,
                    'userid' => Yii::app()->user->id,
                    'text' => CHtml::encode($msg),
                    'id' => $id = $chat_array[count($chat_array) - 1]->id+1,
                );

            }
            file_put_contents($dbfile, json_encode($chat_array));
            echo json_encode(array(
                'result' => true,
                'data' => json_encode($chat_array[count($chat_array)-1]),
                'id' => $id,
            ));
            die();
        }
    }

    public function actionUpdateActiveUser() {
        if(!Yii::app()->user->isGuest) {
            $user_id = $this->getUserId();
            $user_name = Yii::app()->user->name;
            $_chanelName = ($_GET['chanel']) ? $_GET['chanel'] : false;
            if(!$_chanelName) return false;

            $dbfile = dirname(__FILE__) . "/../../chat_data/chanel_list.txt";
            $chanel_list = json_decode(file_get_contents($dbfile));

            $chanel_list->$_chanelName->user_list->$user_name->update_time = time();

            file_put_contents($dbfile, json_encode($chanel_list));

        }

    }

    public function actionChangeChanel() {
        $_chanelOld = (isset($_REQUEST['chanel_name_old'])) ? $_REQUEST['chanel_name_old'] : false;
        $_chanelNew = (isset($_REQUEST['chanel_name_new'])) ? $_REQUEST['chanel_name_new'] : false;

        if(!$_chanelNew || Yii::app()->user->isGuest) return false;

        $user_name = Yii::app()->user->name;

        $userTimeLiveInChat = 30;

        $dbfile = dirname(__FILE__) . "/../../chat_data/chanel_list.txt";
        $chanel_list = json_decode(file_get_contents($dbfile));


        foreach($chanel_list as $name => $chanel_info) {
            $chanel_info->user_list = (array)$chanel_info->user_list;

            if($name == $_chanelNew) {

                $chanel_info->user_list[$user_name] = array(
                    'userid' => Yii::app()->user->id,
                    'update_time' => time(),
                );

            } else {
                unset($chanel_info->user_list[$user_name]);
            }


            if(count($chanel_info->user_list) > 0) {
                $chanel_info->user_list = (array)$chanel_info->user_list;
                foreach($chanel_info->user_list as $us_name => $us_data) {
                    $us_data = (array)$us_data;

                    if(@$us_data['update_time'] + $userTimeLiveInChat < time()) {

                        unset($chanel_info->user_list[$us_name]);
                    }
                }
            }


        }
        file_put_contents($dbfile, json_encode($chanel_list));
    }

    public function actionCreateChanel() {

        $_chanelName = ($_POST['chanel_name']) ? $_POST['chanel_name'] : false;
        preg_match_all('/[a-zA-Z0-9\_\-]+/si', $_chanelName, $result);
        $_chanelName = $result[0][0];

        if(Yii::app()->user->isGuest) {
            echo json_encode(array(
                'result' => false,
                'message' => Controller::trans("Please need login"),
            ));
            die();
        }

        if($_chanelName) {
            $message = "Chanel created!";
            $result = true;

            $username = Yii::app()->user->name;

            $dbfile = dirname(__FILE__) . "/../../chat_data/chanel_list.txt";
            if(!is_file($dbfile)) {

                $id = 0;
                $chanel_list[$_chanelName] = array(
                    'user_list' => false,
                );

            } else {

                $chanel_list = json_decode(file_get_contents($dbfile));

                $chanel_list = (array)$chanel_list;

                if(in_array($_chanelName, array_keys($chanel_list))) {
                    $message = Controller::trans("Name is already");
                    $result = false;

                } else {
                    $chanel_list[$_chanelName] = array(
                        'user_list' => array(
                            $username => array(
                                'userid' => Yii::app()->user->id,

views/user/_game_comment_list.php
<div class="label-text"><?php echo Controller::trans('Last five comments'); ?></div>
<div class="comment-list">
    <?php if(isset($errors) && is_array($errors) && count($errors)) : ?>
        <?php foreach($errors as $error) : ?>
            <div class="alert in alert-block fade alert-error"><a class="close" data-dismiss="alert">×</a><strong><?php echo Controller::trans('Error!'); ?></strong> <?php echo $error[0]; ?></div>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php if($data->comments) : ?>
    <?php foreach($data->comments as $comment) : ?>
        <div class="comment-block">

            <a title="View profile!" href="<?php  echo Yii::app()->createUrl('user/view', array("id" => $comment->user->id)); ?>"><img src="<?php echo(Profile::getAvatar($comment->user->id)); ?>" alt="<?php echo Controller::trans('Avatar'); ?> " style="width: 50px; height: 50px; float:left; margin-right: 10px;"></a>
            <div class="right">
                <div class="info"><?php echo date("d, F Y" , $comment->date); ?> | <?php echo Controller::trans('Author'); ?> : <?php echo $comment->user->profile->nick; ?><?php if($comment->user_id == Yii::app()->user->id) { ?><div class="delete" value="<?php echo $comment->id; ?>">X</div><?php } ?></div>
                <div class="body"><?php echo $comment->text ;?></div>
            </div>

        </div>
    <?php endforeach; ?>
    <?php else: ?>
        <?php echo Controller::trans('Comments not found'); ?>
    <?php endif; ?>
</div>

views/user/edit.php
<?php
$this->pageTitle=Yii::app()->name . ' - ' . Controller::trans('Edit Profile');

$this->widget('bootstrap.widgets.TbBreadcrumbs', array(
    'links' => array(Controller::trans('View Profile') => array('user/index'), Controller::trans('Edit profile') . " " . Yii::app()->user->name),
));

?>


<div class="span-16">
    <h1><?php echo Controller::trans('Edit profile'); ?></h1>

    <div class="user-profile">
        <div class="span-5">
            <div class="avatar margin-bottom">
                <?php
                echo CHtml::tag('img', array(
                    'src' => Profile::getAvatar($data->id),
                    'id' => 'avatar-url',
                )); ?>
            </div>
            <form id="upload-form" action="<?php echo Yii::app()->createUrl("user/uploadAvatar"); ?>" method="POST" enctype="multipart/form-data">
                <label for="upload-avatar" class="btn btn-success upload-avatar"><?php echo Controller::trans('Upload Avatar'); ?></label>
                <input style="display:none;" type="file" accept="image/x-png, image/gif, image/jpeg" name="avatar" id="upload-avatar"/>
                <?php echo CHtml::tag('a', array(
                    'href' => Yii::app()->createUrl('user/edit'),
                    'class' => 'btn btn-error',
                ), Controller::trans("Cancel")); ?>
            </form>

            <script type="text/javascript">
                $(document).ready(function () {
                    $('#upload-avatar').ajaxfileupload({
                        'action': $("#upload-form").attr('action'),
                        'params': {
                            'extra': 'info'
                        },
                        'onComplete': function(response) {
                            if(response.success) {
                                $('#avatar-url').attr('src', response.patch);
                                $('#new_avatar').val(response.filename);
                                $('.upload-avatar').text(response.msg);
                                $('.upload-avatar').addClass('disabled');
                            }
                        },
                        'onStart': function() {
                            //if(weWantedTo) return false; // cancels upload
                        },
                        'onCancel': function() {
                            $('.upload-avatar').text('Fail upload');
                        }
                    });

                });
            </script>
        </div>
        <div class="span-8">
            <?php /** @var BootActiveForm $form */
            $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
                'id'=>'horizontalForm',
                'type'=>'search',
            )); ?>

            <?php echo $form->textFieldRow($data->profile, 'nick', array('prepend'=>Controller::trans('Display Name'))); ?><br /><br />
            <input type="hidden" id="new_avatar" name="avatar" value="false">
            <?php echo $form->textAreaRow($data->profile, 'sigma', array('class'=>'span4', 'rows'=>5)); ?><br /><br />

            <?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'submit', 'type'=>'info', 'label'=> Controller::trans('Save'))); ?>
            <?php $this->endWidget(); ?>
        </div>
    </div>
</div>

views/user/index.php
<?php
$this->pageTitle=Yii::app()->name . ' - ' . Controller::trans('All members');

$this->widget('bootstrap.widgets.TbBreadcrumbs', array(
    'links' => array(Controller::trans('All users')=> array('user/index'), Controller::trans('Find profile')),
));

?>

<div class="span-18">
<h1><?php echo Controller::trans('All Users'); ?></h1>


<?php foreach($model as $data) : ?>

        <div class="user-list-block-sidebar">
            <div class="img">
                <?php echo CHtml::tag('img',array(
                    "src" => Profile::getAvatar($data->id),
                )); ?>
            </div>

            <div class="context">
                <?php echo CHtml::tag("a", array(
                    "href" => Yii::app()->createUrl("user/view", array("id" => $data->id)),
                    "title" => Controller::trans("View profile"),
                ), (isset($data->profile->nick) ? $data->profile->nick : $data->username)); ?>
                <b style="color: green;">Rating <?php echo $data->points; ?></b>
                <div>
                    <?php echo Controller::trans("Date register") . ' : <br />' . date("j, M Y", $data->date); ?>
                </div>
            </div>
        </div>


<?php endforeach; ?>


</div>

views/user/view.php
<?php
$this->pageTitle=Yii::app()->name . ' - ' . Controller::trans('View Profile') . $data->username;

$this->widget('bootstrap.widgets.TbBreadcrumbs', array(
    'links' => array(Controller::trans('View Profile') => array('user/view', 'id' => $data->id), Controller::trans('Profile') . ' '. $data->getName()),
));

?>
<div class="span-16">

    <div class="user-profile">
        <div class="span-5">
            <div class="avatar margin-bottom">
                <?php
                    echo CHtml::tag('img', array(
                        'src' => Profile::getAvatar($data->id),
                    )); ?>
                </div>
        </div>
        <div class="span-8">
            <h1><?php echo Controller::trans('Profile'); ?> <?php echo $data->getName(); ?></h1>
            <div class="text-label"><?php echo Controller::trans('Sigma'); ?></div>
            <div class="sigma">
                <?php echo CHtml::encode($data->profile->sigma); ?>
            </div>
        </div>
    </div>
</div>