controllers/GameController.php
<?php

class GameController extends Controller
{
	public $layout='column2';

	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

    public $n = 0;


	/**
	 * @return array action filters
	 */
	public function filters()
	{
		//return array(
		//	'accessControl', // perform access control for CRUD operations
		//);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to access 'index' and 'view' actions.
				'actions' => array('index', 'export', 'update', 'unlimited', 'strategy', 'view', 'viewID', 'hrumer', 'nofolow', 'download', 'online', 'rating', 'games', 'community', 'gift', 'giftGame', 'giftCompressor3000', 'giftPage', 'find', 'android'),
				'users' => array('*'),
			),
			array('allow', // allow authenticated users to access all actions
                'actions' => array('admin'),
				'users' => array('@'),
			),
			array('deny',  // deny all users
				'users' => array('*'),
			),
		);
	}

    public function actionJson() {
        $lang = (isset($_GET['lang'])) ? $_GET['lang'] : 'en';
        $platform = (isset($_GET['platform'])) ? $_GET['platform'] : 'pc';
        $page = (isset($_GET['page'])) ? (int)$_GET['page'] : 1;
        $page = $page - 1;
        $model = new Game();

        $attr = array(
            'lang' => $lang,
            'platform' => $platform,
        );

        if((isset($_GET['genre'])) && trim($_GET['genre']) != "") {
            $attr['genreid'] = $_GET['genre'];
        }

        $games = $model->findAllByAttributes($attr, array('limit' => 5, 'offset' => $page * 5, 'order' => 'releasedate DESC'));

        $genres = new Genre();
        $genres = $genres->findAllByAttributes(array(
            'lang' => $lang,
        ));

        $items = array();

        foreach ($genres as $data) {
            if($data->ispri == "yes") {
                $items[$data->genreid] = $data->name;
            }
        }

        echo json_encode(array("tpl" => $this->renderPartial('json', array(
                'model' => $games,
                'page' => $page,
                'lang' => $lang,
                'platform' => $platform,
            ), true, false),
            "genres" => $items,
            "count" => count($games),
        ));
    }

	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{

		$model = $this->loadModel();
        //$relativeModel = $model->getRelative();

		$this->render('view',array(
			'model' => $model,
            //'relative' => $relativeModel,
		));
	}

    public function actionViewID()
    {

        if(isset($_GET['gameid']))
        {

            $model = new Game();
            $model = $model->findByAttributes(array(
                "gameid" => $_GET['gameid'],
                "lang" => Controller::$currentLang,
            ));

            $this->_model=$model;

        }
        if($this->_model===null)
            throw new CHttpException(404, Controller::trans('The requested page does not exist.'));
			
		header("HTTP/1.1 301 Moved Permanently"); 
		header("Location: " . Yii::app()->createUrl('game/view', array('gameid' => $model->getSName()))); 
		
		Yii::app()->end();

        //$relativeModel = $model->getRelative();

        $this->render('view',array(
            'model' => $model,
            //'relative' => $relativeModel,
        ));
    }

    public function actionRating() {

        $model = Game::model()->findByPk($_POST['gameid']);

        if($model) {
            $selectRating = (isset($_POST['value'])) ? $_POST['value'] : "";

            if($selectRating > 1 && $selectRating <= 5) {
                $newRating = (int)$model->rating + (int)$selectRating;
                $newCountRating = (int)$model->count_rating + 1;
                $model->rating = $newRating;
                $model->count_rating = $newCountRating;
                $model->save();
            }
        }
    }

    public function actionUnlimited() {
        $this->layout = 'column1';
        $this->render('unlimited', array());
    }

    public function actionDownload() {

        $file = $this->rootDir() . '/download_files.txt';
        if(!is_file($file)) {
            file_put_contents($file, serialize(array(
                "download" => 0,
            )));
        }

        $statistic = unserialize(file_get_contents($file));
        $statistic['download']++;
        file_put_contents($file, serialize($statistic));

        $model = Game::model()->findByAttributes(array(
            "gameid" => $_GET['gameid'],
            "lang" => Controller::$currentLang,
        ));

        $fish = new Fish();

        header("HTTP/1.1 302 Moved Permanently");
        if($model->platform == Game::PLATFORM_PC)
            header("Location: " . $fish->getParams('download_pc', $model->gameid, $model->foldername));

        if($model->platform == Game::PLATFORM_MAC)
            header("Location: " . $fish->getParams('download_mac', $model->gameid, $model->foldername));


    }

    public function actionOnline() {
        $model = $this->loadModel();

        $this->render('online', array(
            'model' => $model,
        ));
    }


    public function actionNofolow() {
        header("HTTP/1.1 302 Moved Permanently");
        header("Location: " . base64_decode($_GET['url']));
        Yii::app()->end();
    }

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
        $model = new Game();


        $features = $model->findAllByAttributes(array(
            'lang' => Controller::$currentLang,
            'platform' => Controller::currentPlatform(),
            'hasvideo' => 'yes',
            'hasdwfeature' => 'yes',
        ), array('limit' => 4));

        $models = Game::model()->findAllByAttributes(array(
            "lang" => Controller::$currentLang,
            "platform" => $this->currentPlatform(),
        ), array("limit" => 7, "order" => "gamerank DESC"));

        $news = Game::model()->findAllByAttributes(array(
            "lang" => Controller::$currentLang,
            "platform" => Game::PLATFORM_PC,
            "is_guide" => 0,
        ), array("limit" => 6, "order" => "releasedate DESC"));

		$this->render('index', array(
            'features' => $features,
            'models' => $models,
            'news' => $news,
            'find' => Game::model(),
		));

    }

    public function actionStrategy() {
        $model = Game::model()->findAllByAttributes(array(
            "lang" => Controller::$currentLang,
            "is_guide" => "pc",
        ), array(
            'limit' => '12',
            'condition' => "gamename LIKE '%" . addslashes(@$_POST['Game']['gamename']) . "%'"
        ));

        $this->render('guide', array(
            'model' => $model,
            'find' => Game::model(),
        ));
    }

    public function actionFind() {
        $model = Game::model()->findAllByAttributes(array(
            "lang" => Controller::$currentLang,
            "platform" => "pc",
        ), array(
            'limit' => '12',
            'condition' => "gamename LIKE '%" . addslashes(@$_POST['Game']['gamename']) . "%'"
        ));

        $this->render('find', array(
            'model' => $model,
            'find' => Game::model(),
        ));
    }

    public function actionSubscribe() {

        $model = new Game();

        $model->platform = Controller::currentPlatform();
        $model->lang = Controller::$currentLang;

        $model->postPerPage = 9;


        $dataProvider = $model->search();

        $model = new Subscribe();
        if(isset($_POST['Subscribe'])) {
            $model->attributes = $_POST['Subscribe'];
            if($model->save()) {

                $name='=?UTF-8?B?'.base64_encode($model->name).'?=';
                $subject='=?UTF-8?B?'.base64_encode("Aferon Subscribe").'?=';
                $headers="From: $name <" . Yii::app()->params['adminEmail'] . ">\r\n".
                    "Reply-To: {$model->email}\r\n".
                    "MIME-Version: 1.0\r\n".
                    "Content-Type: text/plain; charset=UTF-8";

                $body='Aferon.com
                Thank you subscribe to...';

                mail($model->email,$subject,$body,$headers);

                Yii::app()->user->setFlash('success', '<strong>Well done!</strong> ' . Controller::trans("Thank you signed"));
            }
        }


        $this->render('subscribe', array(
            'model' => $model,
            'dataProvider' => $dataProvider,
        ));
    }

    public function actionHrumer() {
        $model = Game::model()->findAllByAttributes(array(
            "lang" => Controller::$currentLang,
        ), array(
            "order" => "gamerank DESC",
            "limit" => 4000,
        ));
        shuffle($model);
        $result = array();
        $domain = (isset($_GET['domain'])) ? $_GET['domain'] : $this->domain;
        for($i = 0; $i < 100; $i++) {
            $result[] = "" . @$_GET['text'] . " [url=http://" . $domain . Yii::app()->createUrl('game/view', array('gameid' => $model[$i]->getSName())) . "]" . $model[$i]->getGameName() . "[/url]" .
                    " [url=http://" . $domain . Yii::app()->createUrl('game/view', array('gameid' => $model[$i]->getSName())) . "]" . $model[$i]->getGameName() . " " . Controller::trans("review") . "[/url]<br />";
            $resultTT[] = "http://" . $this->domain . Yii::app()->createUrl('game/view', array('gameid' => $model[$i]->getSName())) . "<br />";
        }

        echo "{" . implode(" | " , $result) . "}<br /><br />";
        echo "{" . implode(" | " , $resultTT) . "}<br /><br />";
        die();

    }



    public function actionGift() {
        $model = $this->loadModel();

        $email_shuffle = (isset($_POST['email_list'])) ? $_POST['email_list'] : false;

views/game/_cgame.php
<div class="">
    <div class="compare-game-block">
        <div class="images bottom-padding">
            <?php echo CHtml::tag("a", array(
                'href' => $data->getUrl(),
                'title' => "View game " . $data->gamename,
            ), CHtml::tag("img", array(
                "src" => Fish::images($data->foldername, "feature"),
            ))); ?>
        </div>

        <div class="right">
            <div class="label-text">
                <?php echo $data->gamename; ?>
            </div>

            <div class="genre bottom-padding">
                <?php /*
                <div class="icon-<?php echo $data->genre->sname; ?>"></div><?php echo $data->genre->name; ?><br />
                */ ?>
            </div>
            <?php echo CHtml::tag("a",
                array(
                    "href" => $data->getUrl(),
                    "_target" => "blank",
                    "class" => "btn btn-warning btn-mini float-left",
                    "title" => Controller::trans("View game") . " " . $data->gamename,
                ), Controller::trans("View"));
            ?>

        </div>

    </div>
</div>

views/game/_compare.php
<h6 class="title label-text" title="<?php echo Controller::trans('What game do you like better?'); ?>">
    <?php echo Controller::trans("AFeroN bonus + 1"); ?>
</h6>

    <div>
                <?php $this->renderPartial('_cgame', array(
                    'data' => $model[0],
                )); ?>
    </div>
    <div>
                <?php $this->renderPartial('_cgame', array(
                    'data' => $model[1],
                )); ?>
    </div>

views/game/_full_view.php
<?php

$this->description = $data->getMedDescription();
$this->image = "http://" . $_SERVER['HTTP_HOST'] . Fish::images($data->foldername, 'screen3');

$this->widget('bootstrap.widgets.TbBreadcrumbs', array(
    'links' => array(
        Game::getPlatforms($data->platform) => Yii::app()->createUrl('game/games', array('platform' => $data->platform)),
        $data->getGenre("name") => Yii::app()->createUrl('game/games', array('platform' => $data->platform, 'genre' => $data->getGenre("sname"))),
        Controller::trans('Download Game'),
    ),
));


?>
    <div class="singl-post">
        <div class="title" >
            <h1><?php echo CHtml::encode($data->getGameName()); ?></h1>


        </div>


        <div class="content">
            <div class="game-info">
                <div style="overflow: hidden;">
                    <?php

                    $array[] = array(
                        "image" => Fish::images($data->foldername, 'screen1'),
                        "alt" => Controller::trans("Game screenshot") . " 1 " . $data->getGameName(),
                        "label" => Controller::trans("Game screenshot") . " 1 " . $data->getGameName(),
                        // "caption" => $data->shortdesc,
                    );
                    $array[] = array(
                        "image" => Fish::images($data->foldername, 'screen2'),
                        "alt" => Controller::trans("Game screenshot") . " 2 " . $data->getGameName(),
                        "label" => Controller::trans("Game screenshot") . " 2 " . $data->getGameName(),
                        // "caption" => $data->shortdesc,
                    );
                    $array[] = array(
                        "image" => Fish::images($data->foldername, 'screen3'),
                        "alt" => Controller::trans("Game screenshot") . " 3 " . $data->getGameName(),
                        "label" => Controller::trans("Game screenshot") . " 3 " . $data->getGameName(),
                        // "caption" => $data->shortdesc,
                    );


                    ?>

                    <?php $this->widget('bootstrap.widgets.TbCarousel', array(
                        'htmlOptions' => array('class' => "galley"),
                        'items' => $array,
                    ));

                    ?>

                    <div class="property">

                        <div style="padding: 5px 0">
                            <?php if($_SERVER['HTTP_HOST'] != 'localhost') : ?>
                            <div class="google-adsense google-adsense-widget" >
                                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
								<!-- aferon -->
								<ins class="adsbygoogle"
									 style="display:inline-block;width:250px;height:250px"
									 data-ad-client="ca-pub-9710740179130354"
									 data-ad-slot="2843747982"></ins>
								<script>
								(adsbygoogle = window.adsbygoogle || []).push({});
								</script>
                            </div>
                            <?php endif; ?>
                        </div>


                    </div>


                </div>

                <?php $this->renderPartial('share_buttons'); ?>

                <div class="overflow system">

                    <div class="span-7">
                        <?php
                        if(isset($data->bullet1)) {
                            echo CHtml::tag("b", array(), Controller::trans("Bullet"));
                            echo "<ul>";

                            echo CHtml::tag("li", array() , $data->bullet1);

                            if(isset($data->bullet2)) {
                                echo CHtml::tag("li", array() , $data->bullet2);
                            }
                            if(isset($data->bullet3)) {
                                echo CHtml::tag("li", array() , $data->bullet3);
                            }
                            if(isset($data->bullet4)) {
                                echo CHtml::tag("li", array() , $data->bullet4);
                            }
                            if(isset($data->bullet5)) {
                                echo CHtml::tag("li", array() , $data->bullet5);
                            }
                            echo "</ul>";


                        }
                        ?>


                    </div>
                    <div class="span-7">
                        <?php
                        $request = json_decode($data->systemreq);

                        if($request) {

                            echo CHtml::tag("b", array(), Controller::trans("Min System request"));
                            $array_key_replace_request = array(
                                "sysreqos" => "OS",
                                "sysreqmhz" => "CPU",
                                "sysreqmem" => "Memory",
                                "sysreqdx" => "DiretX",
                                "sysreqhd" => "Hard driver (MB)",
                            );

                            echo "<ul>";
                            foreach($request as $platform => $params) {
                                foreach($params as $key => $req) {
                                    echo "<li>" . str_replace(array_keys($array_key_replace_request), array_values($array_key_replace_request), $key) . " : " . $req . "</li>";
                                }
                            }
                            echo "</ul>";

                        }
                        ?>
                    </div>

                </div>
                <div class="clear"></div>
            </div>

            <div class="long-desc">
                <h2 style="font-size: 14px;" class="label-text">Review for game <?php echo $data->getGameName(); ?></h2>
                 <p><?php echo $data->getLongDescription(); ?></p>
            </div>


            <div class="button-group">
                <?php $this->renderPartial('_buttons', array(
                    'data' => $data,
                )); ?>

                <?php


                    if(isset($data->oggameid)) {
                        echo CHtml::tag("a", array(
                            "href" => Yii::app()->createUrl('game/online', array('gameid' => $data->getSName())),
                            "_target" => "blank",
                            "class" => "playOnline btn btn-danger btn-small",
                            "title" => Controller::trans("Play online game") . " : " . $data->getGameName(),
                            ), Controller::trans("Play Online"));

                    }

                    if(isset($data->macgameid)) {
                        echo CHtml::tag("a", array(
                            "href" => Yii::app()->createUrl('game/download', array('gameid' => $data->macgameid)),
                            "_target" => "blank",
                            "class" => "btn btn-info btn-small",
                            "title" => Controller::trans("Download mac game") . " : " . $data->getGameName(),
                            ),
                            Controller::trans("Download MAC"));

                    }

                    if(isset($data->pcgameid)) {
                        echo CHtml::tag("a", array(
                            "href" => Yii::app()->createUrl('game/download', array('gameid' => $data->pcgameid)),
                            "_target" => "blank",
                            "class" => "btn btn-warning btn-small",
                            "title" => Controller::trans("Download pc game") . " : " . $data->getGameName(),
                            ) , Controller::trans("Download PC"));

                    }

                ?>


                <?php $this->renderPartial('_watch_video', array(
                    'data' => $data,
                )); ?>
                <div class="btn btn-inverse" link="<?php echo Fish::getParams('purchase_game', $data->gameid, $data->foldername); ?>&tryGame=<?php echo $data->gameid; ?>&cid=gamegift" onclick="document.location.href=$(this).attr('link');"><?php echo Controller::trans("Gift Game"); ?></div>

 <br/>


                <br />
            </div>


            <br />
            <br />


            <div class="label-text"><?php echo Controller::trans('Review at a glimpse'); ?></div>
            <div class="well span-15">
                <div class="wall-point">
                    <div class="span-7">
                        <div class="label-text"><?php echo Controller::trans('Genre'); ?> : <?php echo $data->getGenre("name"); ?></div>
                        <p><?php echo $data->getGenre("description"); ?></p>

                        <div class="label-text"><?php echo Controller::trans('Date release'); ?></div>
                        <p><?php echo date('F j, Y', strtotime($data->releasedate)); ?></p>


                    </div>
                    <div class="span-6">


                        <?php if($data->platform != 'og') : ?>
                        <div class="label-text" style="margin-left: 70px;"><?php echo Controller::trans('Five free minutes'); ?></div>
                        <div style="background: url('/css/images/subscribe.png'); width: 229px; height: 44px;">
                            <div style="color: #E4E4E4;  font-size: 10px; margin-left: 185px; padding-top: 2px; text-shadow: 1px 1px 1px #686767; width: 39px;"><?php echo $data->price; ?></div>
                        </div>
						
                        <?php endif; ?>



                        <div class="label-text"><?php echo Controller::trans('Game Rank'); ?></div>
                        <p><?php echo $data->gamerank; ?> <?php echo Controller::trans('points'); ?></p>

                        <div class="label-text"><?php echo Controller::trans('Please rate the game'); ?></div>

                        <b itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
                            <span itemprop="ratingValue"><?php echo $data->rating / $data->count_rating; ?></span> /
                            <span itemprop="reviewCount"><?php echo $data->count_rating; ?></span>
                        </b> &nbsp;
                        <b><?php echo Controller::trans('Rate It'); ?>:</b> <div data-productid="<?php echo $data->gameid; ?>" class="rateit" data-rateit-value="<?php echo $data->rating / $data->count_rating; ?>"></div>


                    </div>
                </div>

                <div class="tagline clear">
                    <h2 class="label-text"><?php echo Controller::trans('Tag line'); ?></h2>
                    <?php
                        $genreIds = explode(",", $data->allgenreid);

                        foreach(Controller::$genreList as $genre) {
                           if(in_array($genre->id, $genreIds)) {
                               echo CHtml::tag("a", array(
                                      'href' => Yii::app()->createUrl("game/games", array('tag' => $genre->sname, 'platform' => Controller::currentPlatform())),
                                      'class' => 'tag-genre',
                                      'title' => Controller::trans("View all games with tag") . " " . $genre->name,
                                   ), $genre->name);
                           }
                        }
                    ?>
                </div>
            </div>



            <br />
            <br />

        </div>


        <br /> <br />


    </div>
<div class="clear"></div>

views/game/index.php
<?php
    $this->pageTitle = Yii::app()->name . ' - ' . Game::getPlatforms(Controller::currentPlatform());

?>

<div class="right-sidebar">
    <div class="top-seven" value="<?php echo @date("N"); ?>">

        <div class="portlet-decoration">
            <div class="portlet-title"><?php echo Controller::trans("Top 7 Games"); ?> ( <?php echo @date("l"); ?> )</div>
        </div>
        <div class="bb">
            <?php foreach($models as $data) { ?>
                <?php $this->renderPartial('_home_view', array(
                    'data' => $data,
                )); ?>
            <?php } ?>
            <script>
                $('.bb').find('.special-item-right').eq(<?php echo @date("N"); ?>-1).addClass("currentWeek");
            </script>
        </div>
    </div>


    <div class="top-seven"">
        <div class="portlet-decoration">
            <div class="portlet-title"><?php echo Controller::trans("Find us on Facebook"); ?></div>
        </div>
        <div class="bb">
            <div class="fb-like-box" data-href="https://www.facebook.com/download.fun.games" data-width="250" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>
        </div>
    </div>

    <?php  $this->widget('Interview', array(
        'title' => Controller::trans("Comments on Games"),
    )); ?>

    <?php /*<div id="compare">
    </div> */ ?>


</div>

<div class="main">

    <b style="text-shadow: 1px 1px 1px #FFFFFF; color: #ADADAD; margin: 0 0 5px 20px;"><?php echo Controller::trans("Example:"); ?> </b> <span style="color: #0E85CD">Lost in Reefs 2</span> <br />
    <div class="qgame">

        <?php  $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
            'id'=>'searchForm',
            'type'=>'search',
            'action' => Yii::app()->createUrl('game/find'),
            //'htmlOptions'=>array('class'=>'well'),
        )); ?>

        <?php echo $form->textFieldRow(Game::model(), 'gamename', array('class'=>'input-medium', 'style' => 'width: 380px;')); ?>
        <?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'submit', 'htmlOptions' => array('class' => 'btn-info'), 'label'=>'Find')); ?>

        <?php $this->endWidget();  ?>

    </div>

<div class="label-text"><?php echo Controller::trans("Featured Games"); ?></div>
    <div class="feature">
        <ul>
        <?php if(is_array($features) && count($features) > 0) {
            foreach ($features as $id => $data) { ?>

            <?php

            echo CHtml::tag("li",array(), CHtml::tag("a", array(
                'href' => $data->getUrl(),
                'title' => Controller::trans('View images'),
                'video' => '
                    <object
                        type="application/x-shockwave-flash"
                        id="kt_player_internal"
                        name="kt_player_internal"
                        data="/css/player.swfx"
                        width="316"
                        height="254">
                        <param name="allowfullscreen" value="true">
                        <param name="allowscriptaccess" value="always">
                        <param name="bgcolor" value="000000">
                        <param name="flashvars" value="video_url=' . urlencode(sprintf("http://cdn-games.bigfishsites.com/%s/%s.flv", $data->foldername, $data->foldername)) . '%2F&amp;video_id=3805&amp;license_code=87ccba8ba9ba16a2577df6a86ed97705&amp;postfix=.mp4&amp;timeline_screens_url=%3Fmode%3Dasync%26action%3Dtimelines%26count%3D104%26video_id%3D3805%26format%3D.mp4%26rnd%3D1380219136&amp;timeline_screens_interval=10&amp;preview_url=' . urlencode(Fish::images($data->foldername, "screen1")) . '&amp;skin=1&amp;bt=3&amp;hide_controlbar=0&amp;embed=0&amp;internal_id=kt_player_internal">
                    </object>
                ',
            ), CHtml::tag('img', array(
                'src' => Fish::images($data->foldername, 'screen1'),
                'alt' => $data->getGameName(),
            )) ));

            ?>


        <?php } } ?>
        </ul>

        <div class="preload">
            <div class="ctn">
                <div class="embed_feature">

                    <object
                        type="application/x-shockwave-flash"
                        id="kt_player_internal"
                        name="kt_player_internal"
                        data="/css/player.swfx"
                        width="316"
                        height="254">
                        <param name="allowfullscreen" value="true">
                        <param name="allowscriptaccess" value="always">
                        <param name="bgcolor" value="000000">
                        <param name="flashvars" value="video_url=<?php echo urlencode(sprintf("http://cdn-games.bigfishsites.com/%s/%s.flv", $data->foldername, $data->foldername)); ?>%2F&amp;video_id=3805&amp;license_code=87ccba8ba9ba16a2577df6a86ed97705&amp;postfix=.mp4&amp;timeline_screens_url=%3Fmode%3Dasync%26action%3Dtimelines%26count%3D104%26video_id%3D3805%26format%3D.mp4%26rnd%3D1380219136&amp;timeline_screens_interval=10&amp;preview_url=<?php echo urlencode(Fish::images($data->foldername, "screen1")); ?>&amp;skin=1&amp;bt=3&amp;hide_controlbar=0&amp;embed=0&amp;internal_id=kt_player_internal">
                    </object>

                </div>
            </div>
            <div class="label-text"><div class="icon-play pull-left"></div><b><?php echo Controller::trans("Play Now"); ?> &nbsp;</b><a href="<?php echo $data->getUrl(); ?>"><?php echo $data->getGamename(); ?></a></div>
        </div>
    </div>

<br /><br />

    <div class="news">
        <h4 class="label-text"><?php echo Controller::trans("New Games"); ?></h4>
        <ul>
            <li>
                <?php if(is_array($news) && count($news) > 0) {
                foreach ($news as $id => $data) { ?>
                    <div class="news-block">
                        <div class="right pull-left">
                            <div>
                                <a href="<?php echo $data->getUrl(); ?>">
                                    <img src="<?php echo Fish::model()->images($data->foldername, 'feature');  ?>" alt="<?php echo Controller::trans("Feature screenshot game");?> <?php echo $data->gamename; ?>" />
                                </a>
                            </div>
                            <a href="<?php echo $data->getDownloadUrl(); ?>" rel="nofollow" title="<?php echo Controller::trans("Now download Pc Game"); ?> <?php echo $data->gamename; ?>">
                                <div class="btn btn-mini btn-warning font-download"><?php echo Controller::trans("download"); ?></div>
                            </a>
                        </div>
                        <div class="description pull-left">
                            <div class="title">
                                <a href="<?php echo $data->getUrl(); ?>" title="<?php echo Controller::trans("View game"); ?> <?php echo $data->gamename; ?>">
                                    <b class="label-text"><?php echo $data->gamename; ?></b>
                                </a>
                            </div>
                            <div class="desc">
                                <?php echo $data->getMedDescription(); ?>
                            </div>
                            <div class="ff">
                                <?php echo date("j, M Y", strtotime($data->releasedate)); ?> &nbsp; / &nbsp; <i class="icon-<?php echo $data->getGenre('sname'); ?>"></i>
                                <a href="<?php echo Yii::app()->createUrl('game/games', array('platform' => Controller::currentPlatform(), 'genre' => $data->getGenre('sname'))); ?>" title="<?php echo Controller::trans("View games with genre");?> <?php echo $data->getGenre('name'); ?>"><?php echo $data->getGenre('name'); ?></a> &nbsp;
                                / &nbsp; <b><?php echo Controller::trans("Size"); ?> : </b><?php echo $data->gamesize(); ?>
                            </div>
                        </div>

                    </div>
					
                <?php  } } ?>
            </li>
        </ul>

    </div>



    <div class="all label-text"><a title="<?php echo Controller::trans("View all new pc games"); ?>" href="<?php echo Yii::app()->createUrl('game/games', array('platform' => Game::PLATFORM_PC));?>"><?php echo Controller::trans("View all games"); ?>.</a></div>
</div>