controllers/SiteController.php
<?php

class SiteController extends Controller
{
	public $layout='column2';

	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
        $model = Game::model()->findAllByAttributes(array(
            "lang" => Controller::$currentLang,
        ), array(
            'order' => 'releasedate DESC',
            'limit' => 7,
        ));

	    if($error=Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest) {
	    		echo $error['message'];
            }
	    	else {
	        	$this->render('error', array("error" => $error, "model" => $model));
            }
	    }
	}

    public  function actionRobots() {
        $domain = (Controller::$currentLang == "en") ? "" : Controller::$currentLang . ".";
        echo <<<EOD
User-Agent: *
Disallow: /protected/

Sitemap: http://{$domain}aferon.com/sitemap/en_sitemap.xml
EOD;

    }

    public function actionGetSitemap() {
        echo file_get_contents(controller::rootDir() . "/sitemap/" . Controller::$currentLang . "_sitemap.xml");
    }

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{

		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
                Functions::smtpmail(Yii::app()->params['adminEmail'], $model->subject, $model->body . "<br />" . $model->email);
				Yii::app()->user->setFlash('contact', Controller::trans('Thank you for contacting us. We will respond to you as soon as possible.'));
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

    public function actionChat() {
        $this->render('chat');
    }

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model = new LoginForm('login');

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid

			if($model->validate() && $model->login()) {
				$this->redirect(Yii::app()->user->returnUrl);
            }
		}
		// display the login form
		$this->render('login',array('model' => $model));
	}

    public function actionRegister() {


        $model = new LoginForm('register');


        if(isset($_POST['LoginForm']))
        {
            $model->attributes=$_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if($model->validate() && $model->registration()) {
                Yii::app()->user->setFlash('success', sprintf('<strong>Profit!</strong> You have successfully registered. Please %s',
                    CHtml::tag("a", array(
                            "href" => Yii::app()->createUrl('site/login')
                        ), "Login"
                    )
                ));
                $model = new LoginForm('register');
            }
        }

        $this->render('register',array('model' => $model));
    }

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}

    public function actionSitemap() {
        $block = array(
            "platforms" => Game::getPlatforms(),
            "genres" => Genre::model()->findGenres(),
        );
        if(isset($_GET['genre']) && isset($_GET['platform'])) {
            $block['games'] = Game::model()->findAllByAttributes(array(
                "lang" => Controller::$currentLang,
                "genreid" => $_GET['genre'],
                "platform" => $_GET['platform'],
            ));
        }
        $this->render('sitemap', array("block" => $block));
    }
}

views/site/_create_chanel.php
<!-- Button to trigger modal -->
<a href="#create-chanel" role="button" class="btn btn-warning" data-toggle="modal"><?php echo Controller::trans('Create'); ?></a>

<!-- Modal -->
<div style="width: 800px; margin-left: -400px;" id="create-chanel" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="margin-right: 10px;">X</button>
        <h3 id="myModalLabel"><?php echo Controller::trans('Create Chanel'); ?></h3>
    </div>
    <div class="modal-body" style="background: #DAECFF;">
        <div class="span-8">
            <label><?php echo Controller::trans('Chanel name'); ?></label>
            <input type="text" value="" id="chanel_name" />
            <div class="btn btn-success" id="send_chanel_name"><?php echo Controller::trans('Create Chanel'); ?></div>
            <?php if(Yii::app()->user->isGuest) { echo CHtml::tag("a", array("href" => Yii::app()->createUrl('site/login')), Controller::trans("Need Login")); } ?>
            <div id="result"></div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" id="refresh-chanel" aria-hidden="true"><?php echo Controller::trans('Close'); ?></button>
        <!--<button class="btn btn-primary">Save changes</button>-->
    </div>
</div>

views/site/chat.php
<?php
$this->pageTitle=Yii::app()->name . ' - ' . Controller::trans('Real life Chat');

$this->widget('bootstrap.widgets.TbBreadcrumbs', array(
    'links' => array(Controller::trans('Chat') => array('site/sitemap'), $this->trans('Real life Chat')),
));

?>

<script>

    $(function() {

        var chanel=undefined;

        var chanels = [];

        $('.thd #buttonStateful').click(function() {

            if(chanel == undefined) {
                $('#message-result-send-message').text('<?php echo Controller::trans("Please select chanel"); ?>');
                return false;
            }

            var txt = $('.thd .comment');
            if($(txt).val() != '') {
                $.ajax({
                    url: '/user/send?chanel='+chanel, //your server side script
                    data: { msg: $(txt).val() }, //our data
                    type: 'POST',
                    dataType: 'JSON',
                    success: function (data) {
                        $(txt).val('');
                        refreshChat();
                        $('#message-result-send-message').html(data.message);
                    }
                });
            } else {
                $('#message-result-send-message').text('<?php echo Controller::trans("Please write message text!"); ?>');
            }
        });

        var refreshChanel = function() {
            $.ajax({
                url: '/chat_data/chanel_list.txt?r='+Math.random() * (9999999 - 999999), //your server side script
                dataType: 'JSON',
                success: function (data) {

                    var mass = '';
                    for(name in data) {
                        chanels.push(name);
                        var active = (name == chanel) ? ' active' : '';
                        mass += '<li class="chanel_id">';
                        mass += '<div class="chanel-info'+active+'"><div class="chanel-name name">' + name + '</div>';
                        mass += '</div>';
                        mass += '<div class="chanel-name user_list">';
                        for(login in data[name].user_list) {
                            mass += '<div class="user_item" value="' + data[name].user_list[login].userid + '">' + login + '</div>';
                        }
                        mass += '</div>';
                        mass += '</li>';
                    }
                    $('#chanel-item').html(mass);

                    //alert(chanels.shift());
                    //changeChanel(chanel, chanels.shift());
                }
            });
        };



        var refreshChat = function() {

            if(chanel == undefined) {
                $('#message-result-send-message').text('<?php echo Controller::trans("Please select chanel"); ?>');
                return false;
            }

            $.ajax({
                url: '/chat_data/'+chanel+'.txt?t'+Math.random() * (9999999 - 999999), //your server side script
                dataType: 'JSON',
                success: function (data) {
                    var mass = '';
                    for(id in data) {
                        mass += '<li>'+data[id].username+' : '+data[id].text+'</li>';
                    }

                    $('#chat-item').html(mass);
                }
            });
        }

        var sendIsActive = function() {
            if(chanel == undefined) {
                $('#message-result-send-message').text('<?php echo Controller::trans("Please select chanel"); ?>');
                return false;
            }
            $.ajax({
                url: '/user/updateActiveUser?chanel='+chanel+'&t'+Math.random() * (9999999 - 999999), //your server side script
                dataType: 'JSON',
                success: function (data) {
                    //qwe;
                }
            });
        }

        refreshChanel();

        $('#refresh-chanel').click(function() {
            refreshChanel();
            return false;
        });

        $('.chanel-info').live('click', function() {
            setChanel($(this).find('.name').text());
        });


        setInterval(function() {
            refreshChat();
        }, 1000);

        setInterval(function() {
            sendIsActive();
            refreshChanel();
        }, 10000);

        $('#send_chanel_name').click(function() {
            var _chanel_name = $('#chanel_name').val();
            $.ajax({
                url: '/user/createChanel', //your server side script
                data: { chanel_name: _chanel_name }, //our data
                type: 'POST',
                dataType: 'JSON',
                success: function (data) {
                    $('#result').html(data.message);
                    refreshChanel();
                }
            });
        });


        var changeChanel = function(ch_old, ch_new) {
            if(ch_old == ch_new) {
                return false;
            }

            $.ajax({
                url: '/user/changeChanel',
                data: { chanel_name_new: ch_new, chanel_name_old: ch_old }, //our data
                type: 'POST',
                dataType: 'JSON',
                success: function (data) {
                    refreshChanel();

                }
            });
        }

        var setChanel = function(name) {
            changeChanel(chanel, name);
            chanel = name;
            $('#message-result-send-message').text("");
            $('#current_chanel').text(chanel);
            refreshChat();
        }




    });



</script>

<h1 class="label-text"><?php echo Controller::trans('User Communication'); ?></h1>


    <div id="chat">
        <div class="pull-left body span-12">
            <ul id="chat-item">

            </ul>
        </div>
        <div class="pull-left chanel span-4">
            <h5><?php echo Controller::trans("Chanel's"); ?> <a href="#" id="refresh-chanel" class="icon-refresh"></a></h5>
            <div class="chanel-list">
                <ul id="chanel-item">
                </ul>
            </div>
            <b><?php echo Controller::trans('New Chanel'); ?></b>
            <?php $this->renderPartial('_create_chanel');  ?>
        </div>

    </div>

    <div class="thd span-17" style="padding: 5px 15px;border: 1px solid #D3D3D3; background: #FDFDF0;">
        <div style="padding: 5px 10px; display: inline-block;"><b id="current_chanel"></b> : <?php echo Yii::app()->user->name; ?></div>
        <input type="text" class="comment" name="comment" style="width:130px; margin: 0 10px 0 0;">

        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType' => 'button',
            'type' => 'primary',
            'label' => Controller::trans('Send'),
            'loadingText' => 'loading...',
            'htmlOptions' => array(
                'id' => 'buttonStateful'
            ),
        )); ?>
        <b id="message-result-send-message"></b>
    </div>

views/site/contact.php
<?php
$this->pageTitle=Yii::app()->name . ' - ' . Controller::trans('Contact Us');

$this->widget('bootstrap.widgets.TbBreadcrumbs', array(
    'links' => array(Controller::trans('Contact')=>'#', Controller::trans('Contact With AFeroN')),
));

?>

<div class="span-18">

<h1><?php echo Controller::trans('Contact Us'); ?></h1>

<?php if(Yii::app()->user->hasFlash('contact')): ?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('contact'); ?>
</div>

<?php else: ?>

<p>
    <?php echo Controller::trans('If you have any problems, You can contact us on the form. Here are accepted exclusively connected with the problems of customers. If you have problems with installing the game, or does not correct its behavior, please contact'); ?> <a href="http://bigfishgames.custhelp.com/app/home"><?php echo Controller::trans('there'); ?></a>
</p>
<p>
    <?php echo Controller::trans('If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.'); ?>
</p>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm'); ?>

	<p class="note"><?php echo Controller::trans('Fields with'); ?> <span class="required">*</span> <?php echo Controller::trans('are required'); ?>.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'subject'); ?>
		<?php echo $form->textField($model,'subject',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model, 'body'); ?>
		<?php echo $form->textArea($model, 'body', array('rows'=>6, "style" => "width:600px; max-width: 600px;")); ?>
	</div>

	<?php if(CCaptcha::checkRequirements()): ?>
	<div class="row">
		<?php echo $form->labelEx($model, 'verifyCode'); ?>
		<div style="background: #FFF; padding: 10px; width: 300px; border-radius: 12px; margin-bottom: 10px;">
		<?php $this->widget('CCaptcha'); ?><br />
		<?php echo $form->textField($model,'verifyCode'); ?>
		</div>
		<div class="hint"><?php echo Controller::trans('Please enter the letters as they are shown in the image above.'); ?>
		<br/><?php echo Controller::trans('Letters are not case-sensitive.'); ?></div>
	</div>
	<?php endif; ?>

	<div class="row submit">
		<?php echo CHtml::submitButton('Submit', array('class' => 'btn btn-info')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php endif; ?>

</div>

views/site/error.php
<?php
$this->pageTitle=Yii::app()->name . ' - ' . Controller::trans('Page not found');
$this->widget('bootstrap.widgets.TbBreadcrumbs', array(
    'links' => array('Error'),
));
?>
<div class="span-16">


<h2><?php echo Controller::trans('Error'); ?> <?php echo $error['code']; ?></h2>

<div class="error">
<?php echo CHtml::encode($error['message']); ?>
</div>


    <?php if(is_array($model) && count($model) > 0) : ?>
        <?php foreach($model as $data) : ?>
            <div class="news-block">
                <div class="right pull-left">
                    <div>
                        <a href="<?php echo $data->getUrl(); ?>">
                            <img src="<?php echo Fish::model()->images($data->foldername, 'feature'); ?>" alt="<?php echo Controller::trans("Feature screenshot game");?> <?php echo $data->gamename; ?>" />
                        </a>
                    </div>
                    <a href="<?php echo Yii::app()->createUrl('game/download', array('gameid' => $data->gameid)); ?>" title="<?php echo Controller::trans("Now download Pc Game"); ?> <?php echo $data->gamename; ?>">
                        <div class="btn btn-mini btn-warning font-download">download</div>
                    </a>
                </div>
                <div class="description pull-left">
                    <div class="title">
                        <a href="<?php echo $data->getUrl(); ?>" title="<?php echo Controller::trans("View game"); ?> <?php echo $data->gamename; ?>">
                            <b class="label-text"><?php echo $data->gamename; ?></b>
                        </a>
                    </div>
                    <div class="desc">
                        <?php echo $data->getMedDescription(); ?>
                    </div>
                    <div class="ff">
                        <?php echo date("j, M Y", strtotime($data->releasedate)); ?> &nbsp; / &nbsp; <i class="icon-<?php echo $data->getGenre('sname'); ?>"></i>
                        <a href="<?php echo Yii::app()->createUrl('game/games', array('platform' => Controller::currentPlatform(), 'genre' => $data->getGenre('sname'))); ?>" title="<?php echo Controller::trans("View games with genre");?> <?php echo $data->getGenre('name'); ?>"><?php echo $data->getGenre('name'); ?></a> &nbsp;
                        / &nbsp; <b><?php echo Controller::trans("Size"); ?> : </b><?php echo $data->gamesize(); ?>
                    </div>
                </div>

            </div>
        <?php endforeach; ?>
    <?php endif; ?>

</div>

views/site/login.php
<?php

$this->widget('bootstrap.widgets.TbBreadcrumbs', array(
    'links' => array('Login'=>array("site/login"), Controller::trans('Login in Community')),
));
?>

<div class="span-16">
<h1><?php echo Controller::trans('Login'); ?></h1>

<p><?php echo Controller::trans('Please fill out the following form with your login credentials:'); ?></p>

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableAjaxValidation'=>true,
)); ?>

	<p class="note"><?php echo Controller::trans('Fields with'); ?> <span class="required">*</span> <?php echo Controller::trans('are required.'); ?></p>


	<div class="row">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username'); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password'); ?>
		<?php echo $form->error($model,'password'); ?>
	</div>

	<div class="row rememberMe">
		<?php echo $form->checkBox($model,'rememberMe'); ?>
		<?php echo $form->label($model,'rememberMe'); ?>
		<?php echo $form->error($model,'rememberMe'); ?>
	</div>

	<div class="row submit">
		<?php echo CHtml::submitButton(Controller::trans('Login'), array('class' => 'btn btn-info')); ?>
        <?php echo CHtml::tag("a", array(
            "href" => Yii::app()->createUrl("site/register"),
        ), Controller::trans("Registration")); ?>
	</div>


    <h2 class="label-text" style="font-size: 14px;">Do you already have an account on one of these sites? Click the logo to log in with it here:</h2>
    <?php Yii::app()->eauth->renderWidget(); ?>



<?php $this->endWidget(); ?>
</div><!-- form -->
</div>

views/site/register.php
<?php
$this->pageTitle = Controller::trans("Registration in Community");
$this->description = Controller::trans("Page of the registration on project AFeroN.com");

$this->widget('bootstrap.widgets.TbBreadcrumbs', array(
    'links' => array('Registration' => array("site/register"), Controller::trans('Registration in Community')),
));
?>
<div class="span-16">
<h1><?php echo Controller::trans('Registration at AFeroN'); ?></h1>

<p><?php echo Controller::trans('Please fill out the following form with your registration credentials:'); ?></p>

    <?php $this->widget('bootstrap.widgets.TbAlert', array(
        'block'=>true, // display a larger alert block?
        'fade'=>true, // use transitions?
        'closeText'=>'&times;', // close link text - if set to false, no close link is displayed
        'alerts'=>array( // configurations per alert type
            'success'=>array('block'=>true, 'fade'=>true, 'closeText'=>'&times;'), // success, info, warning, error or danger
        ),
    )); ?>

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableAjaxValidation'=>true,
)); ?>

	<p class="note"><?php echo Controller::trans('Fields with'); ?> <span class="required">*</span> <?php echo Controller::trans('are required.'); ?></p>

	<div class="row">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username'); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password'); ?>
		<?php echo $form->error($model,'password'); ?>
	</div>

    <div class="row">
        <?php echo $form->labelEx($model,'confirm_password'); ?>
        <?php echo $form->passwordField($model,'confirm_password'); ?>
        <?php echo $form->error($model,'confirm_password'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'email'); ?>
        <?php echo $form->textField($model,'email'); ?>
        <?php echo $form->error($model,'email'); ?>
    </div>

	<div class="row submit">
		<?php echo CHtml::submitButton(Controller::trans('Registration'), array('class' => 'btn btn-info')); ?>
	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->
</div>

views/site/sitemap.php
<?php
$this->pageTitle=Yii::app()->name . ' - ' . Controller::trans('Site Map');

$this->widget('bootstrap.widgets.TbBreadcrumbs', array(
    'links' => array(Controller::trans('Site Map') => array('site/sitemap'), Controller::trans('Site Map AFeroN')),
));

?>
<div class="span-18">

<div class="well" style="overflow: hidden;">
    <h1><?php echo Controller::trans('All Games at Sitemap'); ?></h1>
    <ul>
        <?php foreach($block['platforms'] as $pl => $platform) : ?>
            <li class="span-4"><a href="<?php echo Yii::app()->createUrl('game/index', array('platform' => $pl)); ?>"><?php echo $platform; ?></a>
                <ul>
                    <?php foreach($block['genres'] as $genre) : ?>
                        <li><a class="loadGames" href="<?php echo Yii::app()->createUrl('site/sitemap', array('genre' => $genre->genreid, 'platform' => $pl)); ?>"><?php echo $genre->name; ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </li>
        <?php endforeach; ?>
    </ul>


</div>

<?php if(isset($block['games']) && is_array($block['games']) && count($block['games'])) { ?>
<div class="label-text"><?php echo Controller::trans('Games with'); ?> <?php echo Game::getPlatforms($block['games'][0]->platform); ?> :: <?php echo $block['games'][0]->genre->name; ?> :: <?php echo Yii::app()->params['langs'][$block['games'][0]->lang]; ?></div>
<div class="well gamesBlock">
    <ul>
    <?php foreach($block['games'] as $game) : ?>
        <li><?php
            echo CHtml::tag("a", array(
                "href" => $game->getUrl(),
                "title" => "View game : " . $game->gamename,
            ), $game->gamename);
        ?></li>
    <?php endforeach; ?>
    </ul>
</div>
<?php } ?>

    </div>

views/site/sitemap_xml.php
<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<urlset
    xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
    <?php if(is_array($model) && count($model) > 0) : ?>
        <?php foreach($model as $data) : ?>
            <url>
                <loc>http://<?php echo ($data->lang == 'en') ? "" : $data->lang . "."; ?>aferon.com<?php echo Yii::app()->createUrl("game/view", array("gameid" => $data->gameid)); ?></loc>
                <lastmod><?php echo date("Y-m-d", strtotime($data->releasedate)); ?></lastmod>
                <changefreq>weekly</changefreq>
                <priority>1</priority>
            </url>
        <?php endforeach; ?>
    <?php endif;?>
</urlset>