models/Club.php
<?php

class Club extends CActiveRecord
{
    /**
     * The followings are the available columns in table 'tbl_tag':
     * @var integer $id
     * @var string $name
     * @var integer $frequency
     */
    public $name = null;

    public $postPerPage = 9;

    /**
     * Returns the static model of the specified AR class.
     * @return CActiveRecord the static model class
     */
    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{club}}';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            //array('sname', 'required'),
            //array('sname', 'unique'),
            //array('trackId, kind, artistId, features, supportedDevices, isGameCenterEnabled, screenshotUrls, ipadScreenshotUrls, artworkUrl60, artworkUrl512, artistViewUrl, artistName, price, version, description, currency, genres, genreIds, releaseDate, sellerName, bundleId, trackName,  primaryGenreName, primaryGenreId, releaseNotes, formattedPrice, wrapperType, trackCensoredName, lang, fileSizeBytes, sellerUrl, contentAdvisoryRating, averageUserRatingForCurrentVersion, userRatingCountForCurrentVersion, artworkUrl100, trackViewUrl, trackContentRating, averageUserRating, userRatingCount', 'safe'),
            //array('frequency', 'numerical', 'integerOnly'=>true),
            //array('name', 'length', 'max'=>128),
            //array('trackId+lang', 'application.extensions.uniqueMultiColumnValidator'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'promo' => array(self::HAS_MANY, 'ClubPromotion', array('club_id' => 'id', 'lang' => 'lang')),
        );
    }

    public function getPromo($type = 'fun-art') {
        $result = array();
        foreach ($this->promo as $data) {
            if($data->type == $type) {
                $result[] = $data;
            }
        }
        return $result;
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            "id" => "id",
            "lang" => "Language",
            "name" => "Club name",
            "description" => "Description",
            "meta_description" => "Meta description",
            "url_developer" => "Developer Url",
            "sname" => "Patch Name",
        );
    }

    public static function snameToName($sname) {
        $sname = str_replace("-", " ", $sname);
        if (!function_exists('mb_ucfirst') && extension_loaded('mbstring'))
        {
            /**
             * mb_ucfirst - преобразует первый символ в верхний регистр
             * @param string $str - строка
             * @param string $encoding - кодировка, по-умолчанию UTF-8
             * @return string
             */
            function mb_ucfirst($str, $encoding='UTF-8')
            {
                $str = mb_ereg_replace('^[\ ]+', '', $str);
                $str = mb_strtoupper(mb_substr($str, 0, 1, $encoding), $encoding).
                    mb_substr($str, 1, mb_strlen($str), $encoding);
                return $str;
            }
        }
        return mb_ucfirst($sname);
    }

    public static function nameToSName($name) {
        //preg_match_all("//");
    }


    public function search()
    {
        $criteria=new CDbCriteria;

        $criteria->compare('lang', $this->lang);

        if($this->name) {
            $criteria->addSearchCondition('name', $this->name);
        }

        return new CActiveDataProvider('Club', array(
            'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => $this->postPerPage,
            ),
            'sort' => array(
                'defaultOrder' => 'date, rank DESC',
            ),
        ));
    }

}

models/Game.php
<?php

/**
 * Class Post
 */
class Game extends CActiveRecord
{
	/**
	 * The followings are the available columns in table 'tbl_post':
	 * @var integer $id
	 * @var string $title
	 * @var string $content
	 * @var string $tags
	 * @var integer $status
	 * @var integer $create_time
	 * @var integer $update_time
	 * @var integer $author_id
	 */

    const PLATFORM_PC = "pc";
    const PLATFORM_MAC = "mac";
    const PLATFORM_OG = "og";



    public $platform = self::PLATFORM_PC;
    public $postPerPage = '9';

    public $tag = false;

	/**
	 * Returns the static model of the specified AR class.
	 * @return CActiveRecord the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}


    /**
     * @param int $platformId
     * @return mixed
     */
    public static function getPlatforms($platform = null) {

        if($platform) {
            $platforms = self::getPlatforms();
            return (isset($platforms[$platform])) ? $platforms[$platform] : null;
        }

        return array(
            self::PLATFORM_PC => Controller::trans("PC Games"),
            self::PLATFORM_MAC => Controller::trans("MAC Games"),
            self::PLATFORM_OG => Controller::trans("Online Games"),
        );

    }

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{games}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('gamename, meddesc, platform, lang', 'required'),
			array('platform', 'in', 'range' => array_keys(Game::getPlatforms())),
			array('gamename', 'length', 'max' => 255),
            array('create_time', 'date', 'format' => 'yyyy-M-d H:m:s'),
            array('gameid+platform+lang', 'application.extensions.uniqueMultiColumnValidator'),
            array('sname, gameid, oggameid, macgameid, pcgameid, rdate, rsname, family, familyid, productid, genreid, allgenreid, shortdesc, longdesc, bullet1, bullet2, bullet3, bullet4, bullet5, foldername, price, hasdownload, hasvideo, hasflash, hasdwfeature, dwwidth, dwheight, gamerank, releasedate, gamesize, systemreq, onlineiframeheight, onlineiframewidth, author_id, create_time', 'safe'),

            array('gamename, platform, lang', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			//'author' => array(self::BELONGS_TO, 'User', 'author_id'),
			//'comments' => array(self::HAS_MANY, 'Comment', 'id', 'condition' => 'comments.status='.Comment::STATUS_APPROVED, 'order'=>'comments.create_time DESC'),
			//'commentCount' => array(self::STAT, 'Comment', 'id', 'condition' => 'status='.Comment::STATUS_APPROVED),
            'genre' => array(self::BELONGS_TO, 'Genre', array('genreid' => 'genreid', 'lang' => 'lang')),
            'sync' => array(self::HAS_ONE, 'Sync', array('gameid' => 'gameid')),
            'comments' => array(self::HAS_MANY, 'Gcomments', array('gameid' => 'gameid'), 'limit' => 5, 'order'=>'date DESC'),
            'reviews' => array(self::HAS_MANY, 'Reviews', array('game_id' => 'gameid')),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'gameid' => 'Game ID',
            'sname' => 'Url Name',
			'gamename' => 'Game Name',
			'lang' => 'Language',
			'platform' => 'Platform',
			'oggameid' => 'Online Game ID',
			'macgameid' => 'Mac Game ID',
			'pcgameid' => 'PC Game ID',
            'family' => 'Family',
            'familyid' => 'Family ID',
            'productid' => 'Product ID',
            'genreid' => 'Genre ID',
            'allgenreid' => 'All Genre ID',
            'shortdesc' => 'Short Description',
            'meddesc' => 'Medium Description',
            'longdesc' => 'Long Description',
            'bullet1' => 'Bullet 1',
            'bullet2' => 'Bullet 2',
            'bullet3' => 'Bullet 3',
            'bullet4' => 'Bullet 4',
            'bullet5' => 'Bullet 5',
            'foldername' => 'Folder Name',
            'price' => 'Price',
            'hasdownload' => 'Has download',
            'hasvideo' => 'Has video',
            'hasflash' => 'Has Flash',
            'hasdwfeature' => 'Has DW Feature',
            'dwwidth' => 'DW width',
            'dwheight' => 'DW height',
            'gamerank' => 'Game Rank',
            'releasedate' => 'Release Date',
            'gamesize' => 'Game Size',
            'systemreq' => 'System Request',
            'onlineiframeheight' => 'Online Iframe Height',
            'onlineiframewidth' => 'Online Iframe Width',
            'author_id' => 'Author ID',
            'create_time' => 'Create Time',
            'img_is_load' => 'Images is Load?',
            'rating' => 'Rating',
            'count_rating' => 'Count Rating',
            'rdate' => 'Rewrite date',
            'rsname' => "Rewrite sname",
		);
	}

    public function getShortDescription(){
        //return $this->shortdesc;
        return (isset($this->sync->short)) ? $this->sync->short : $this->shortdesc;
    }

    public function getMedDescription(){
        //return $this->meddesc;
        return (isset($this->sync->med)) ? $this->sync->med : $this->meddesc;
    }

    public function getLongDescription(){
        //return $this->longdesc;
        return (isset($this->sync->long)) ? $this->sync->long : $this->longdesc;
    }
	
	public function getSeoTitle($default = ''){
        //return $this->longdesc;
        return (isset($this->sync->seo_title)) ? $this->sync->seo_title : $default;
    }
	
	public function getSeoKey($default = ''){
        //return $this->longdesc;
        return (isset($this->sync->seo_key)) ? $this->sync->seo_key : $default;
    }

    public function getGameName(){
        //return $this->gamename;
        return (isset($this->sync->gamename)) ? $this->sync->gamename : $this->gamename;
    }

    public function gamesize()
    {
        $file_size = $this->gamesize;
        if ( 1073741824 <= $file_size )
        {
            $file_size = ( round( $file_size / 1073741824 * 100 ) / 100 )." Gb";
            return $file_size;
        }
        if ( 1048576 <= $file_size )
        {
            $file_size = ( round( $file_size / 1048576 * 100 ) / 100 )." Mb";
            return $file_size;
        }
        if ( 1024 <= $file_size )
        {
            $file_size = ( round( $file_size / 1024 * 100 ) / 100 )." Kb";
            return $file_size;
        }
        $file_size .= " byte";
        return $file_size;
    }

    public function getGenre($param = "name") {

        if(isset($this->genre)) {
            return $this->genre->$param;
        } else {
            $model = $this->genreCreate($this->genreid);
            return "Is created";
        }
    }

    protected function genreCreate($genreid = null) {
        $model = new Genre();
        $model->attributes = Genre::model()->findByAttributes(array(
            'lang' => 'en',
            'genreid' => $genreid,
        ))->getAttributes();
        $model->lang = Controller::$currentLang;
        $model->save();
    }



	/**
	 * @return string the URL that shows the detail of the post
	 */

    public function getSName() {
        if(isset($this->rsname) && $this->rsname != "") {
            return $this->rsname;
        }

        if(isset($this->sname) && $this->sname != "") {
            return $this->sname;
        }

    }

	public function getUrl()
	{

		return Yii::app()->createUrl('game/view', array(
            'gameid' => $this->getSName(),
		));

	}

    public function getDownloadUrl($platform = Game::PLATFORM_PC) {
        return Yii::app()->createUrl('game/download', array(
            'gameid' => $this->gameid,
        ));
    }

    public function getRelative() {

        $model = new $this;
        $model = $model->findAllByAttributes(array(
            'genreid' => $this->genreid,
            'lang' => $this->lang,
            'platform' => $this->platform,
        ), array("limit" => "5", "order" => "gamerank DESC"));
        return $model;
    }

	/**
	 * Retrieves the list of posts based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the needed posts.
	 */
	public function search()
	{
		$criteria=new CDbCriteria;


        $criteria->compare('lang', $this->lang);
		$criteria->compare('platform', $this->platform);
        $criteria->compare('genreid', $this->genreid);
        $criteria->compare('hasdwfeature', $this->hasdwfeature);

        if($this->tag) {
            $criteria->addSearchCondition('allgenreid', $this->tag);
        }

		return new CActiveDataProvider('Game', array(
			'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => $this->postPerPage,
            ),
			'sort' => array(
				'defaultOrder' => 'platform, releasedate DESC',
			),
		));
	}


}

controllers/ClubController.php
<?php

class ClubController extends Controller
{
	public $layout='column1';

	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

    public $n = 0;


	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to access 'index' and 'view' actions.
				'actions' => array('index', 'view', 'find'),
				'users' => array('*'),
			),
			array('allow', // allow authenticated users to access all actions
				'users' => array('@'),
			),
			array('deny',  // deny all users
				'users' => array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{

		$model = $this->loadModel();

		$this->render('view',array(
			'model' => $model,
		));
	}

    public function createPage() {
        $name = $_GET['sname'];

        $model = new Club();
        $model->lang = controller::$currentLang;
        $model->name = Club::snameToName($name);
        $model->sname = $name;
        $model->promotion = 0;
        $model->rank = 0;
        $model->date = time();
        $model->save();
        return $model;
    }



    public function actionCreate() {

    }

    public function actionIndex() {

        $model = new Club();
        $model->lang = Controller::$currentLang;

        if(isset($_POST['Club']['name'])) {
            $model->name = $_POST['Club']['name'];
        }
        $dataProvider = $model->search();

        if(count($dataProvider->data) == 0) {

            $dataProvider->data[] = $this->parser($_POST['Club']['name']);
        }

        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));

    }

    public function parser($name = null) {
        if($name) {
            var_dump($name);
            die();
        }
    }


	public function loadModel()
	{

		if($this->_model===null)
		{

			if(isset($_GET['sname']))
			{

                $model = new Club();
                $model = $model->findByAttributes(array(
                    "sname" => $_GET['sname'],
                    "lang" => Controller::$currentLang,
                ));

                $this->_model=$model;

			}

			if($this->_model===null)
                $this->_model = $this->createPage();
		}

		return $this->_model;
	}
}

views/club/_promotion.php
<div class="club-info">
    <?php foreach($model as $data) : ?>

        <div class="promo-material">
            <div class="<?php echo $data->type; ?>">
                <div class="img">
                    <img class="zoom" src="<?php echo $data->url; ?>"/>
                </div>
                <div class="name" title="<?php echo $data->description; ?>"><?php echo $data->name; ?></div>
            </div>
        </div>

    <?php endforeach; ?>
</div>

views/club/_view.php
<div class="club-item">
    <div class="pull-left">
        <img src="/images/default_avatar.jpg" style="height: 100px;">
    </div>
    <div class="pull-left margin-left">
        <a href="<?php echo Yii::app()->createUrl("club/view", array("sname" => $data->sname)); ?>"><h1><?php echo $data->name; ?></h1></a>
        <p><?php echo $data->description; ?></p>
        <div class="smeta">
            <a href="">Comments (2)</a>
            <a href="">Materials (12)</a>
            <a href="">Subscribers (2011)</a>
        </div>
    </div>

</div>

views/club/index.php
<?php
$this->pageTitle = Controller::trans("Fun art clubs for popular PC | MAC | Ios Games");
$this->description = Controller::trans("Our fun art club, new review every day, Intrigue, Investigation, funny pictures for games.");

?>


<div class="club">

    <?php $this->renderPartial('top-find'); ?>

    <h1 class="label-text">All games clubs</h1>

    <div class="club-body">


        <?php

            $this->widget('zii.widgets.CListView', array(
                'dataProvider' => $dataProvider,
                'itemView' => '_view',
                'ajaxUpdate' => false,
                'template' => "<div style='overflow: hidden;'>{items}\n</div>{pager}",
            ));


        ?>



    </div>
</div>

views/club/top-find.php
<div class="find-club overflow">

    <div class="label-find-club">
        <div style="position: relative;">
            <div class="auth">
                <?php
                if(Yii::app()->user->isGuest) {
                    Yii::app()->eauth->renderWidget();
                }
                ?>
            </div>
            <h1><?php echo Controller::trans("Find your gaming community"); ?></h1>
            <?php  $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
                'id'=>'searchForm',
                'type'=>'search',
                'action' => Yii::app()->createUrl('club/index'),
                //'htmlOptions'=>array('class'=>'well'),
            ));  ?>

            <div style="margin: 10px;">
                <b style="color: green"><?php echo Controller::trans("Example"); ?>: </b> Angry Birds
            </div>
            <?php echo $form->textFieldRow(Club::model(), 'name', array('class'=>'input-medium', 'style' => 'width: 420px')); ?>
            <?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'submit', 'htmlOptions' => array('class' => 'btn-info'), 'label'=>'Find')); ?>

            <?php $this->endWidget(); ?>
        </div>
    </div>
    <img style="position: absolute; top:0; height: 196px; right: 0;" src="/css/images/elf.jpg" alt="<?php echo Controller::trans("girl elf"); ?>" />
</div>

views/club/view.php
<?php
$this->pageTitle = $model->sname . " " . Controller::trans("fun art club.");
$this->description = $model->meta_description;

?>

<div class="club">

    <?php $this->renderPartial('top-find'); ?>

    <div class="club-body">

        <div class="tabs">
            <ul>

                <li class="active"><a href="#tab1" class="tab-active btn btn-warning"><i class="icon-photo"></i><?php echo Controller::trans("Photo"); ?></a></li>
                <li><a href="#tab2" class="tab-active btn btn-success"><i class="icon-video"></i><?php echo Controller::trans("Video"); ?></a></li>
                <li><a href="#tab3" class="tab-active btn btn-info"><i class="icon-music"></i><?php echo Controller::trans("Music"); ?></a></li>
                <li><a href="#tab4" class="tab-active btn"><i class="icon-news"></i><?php echo Controller::trans("Promotion"); ?></a></li>

                <li style="float: right;"><a class="btn" href="<?php echo Yii::app()->createUrl('ios/find', array('name' => $model->name)); ?>"><i class="icon-filefind"></i><?php echo Controller::trans("Download this game!"); ?></a></li>
            </ul>
        </div>

        <div class="look-tabs">

            <div id="tab1" class="tab photo-tab active">
                <h2><?php echo Controller::trans("Fun Art wallpapers"); ?> <?php echo $model->name; ?></h2>

                <?php $this->renderPartial('_promotion', array('model' => $model->getPromo('fun-art'))); ?>
            </div>

            <div id="tab2" class="tab video-tab">
                <h2><?php echo Controller::trans("Video clip"); ?> <?php echo $model->name; ?></h2>

                <?php $this->renderPartial('_promotion', array('model' => $model->getPromo('video'))); ?>
            </div>

            <div id="tab3" class="tab music-tab">
                <h2><?php echo Controller::trans("Music track"); ?> <?php echo $model->name; ?></h2>

                <?php $this->renderPartial('_promotion', array('model' => $model->getPromo('music'))); ?>
            </div>
            <div id="tab4" class="tab news-tab">
                <h2><?php echo Controller::trans("Information about game"); ?> <?php echo $model->name; ?></h2>

                <?php $this->renderPartial('_promotion', array('model' => $model->getPromo('info'))); ?>
            </div>

        </div>

        <?php $this->renderPartial('../ios/share_buttons'); ?>
    </div>
</div>

<script>
    $(function() {

        var typeData = 'video';
        $.ajax({
            url: '/xml/script/parser_content.php',
            dataType: 'JSON',
            type: 'POST',
            data: {type: typeData, name: '<?php echo $model->name; ?>' },
            success: function (data) {
                alert(data);
            }
        });

    });
</script>